<?php

/** @var array $data  */

?>

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Заголовок страницы</title>
  <link rel="stylesheet" href="./styles/style.css">

  <meta property="og:title" content="Заголовок страницы в OG">
  <meta property="og:description" content="Описание страницы в OG">
  <meta property="og:image" content="https://example.com/image.jpg">
  <meta property="og:url" content="https://example.com/">
</head>
<body>
<header>
  <h1>Страница с новостями</h1>
  <nav>
    <ul>
      <li><a href="/">Стартовая страница</a></li>
    </ul>
  </nav>
</header>
<main>
  <article>
    <section>
      <h2>Первая новость</h2>
        <p>контент</p>
        <?php if(isset($data['title'])) : ?>
            <p><?= $data['title'] ?></p>
        <?php endif; ?>
    </section>
    <section>
      <h2>Вторая новость</h2>
        <p>контент</p>
    </section>
  </article>
</main>
<footer>
  <p>Показан раздел с несколькими динамическими параметрами</p>
</footer>
</body>
</html>