<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet" />
<link href="/../css/default.css" rel="stylesheet" type="text/css" media="all" />
<link href="/../css/fonts.css" rel="stylesheet" type="text/css" media="all" />

<!--[if IE 6]><link href="default_ie6.css" rel="stylesheet" type="text/css" /><![endif]-->

</head>
<body>
<div id="header-wrapper">
	<div id="header" class="container">
		<div id="logo">
			<h1><span class="fa fa-bolt"></span><a href="#">Microframework</a></h1>
		</div>
		<div id="menu">
			<ul>
				<li class="current_page_item"><a href="#" accesskey="1" title="">Начальная страница</a></li>
				<li><a href="/news/about/56" accesskey="2" title="">Новости</a></li>
			</ul>
		</div>
	</div>
</div>
<div id="header-featured">
	<div id="banner-wrapper">
		<div id="banner" class="container">
			<h2>Самописный микрофреймворк</h2>
			<p>Написан для <strong>ознакомления</strong> на чистом php, без использования пакетного менеджера. </p>
			<a href="#" class="button">Одобрено</a>
		</div>
	</div>
</div>
<div id="wrapper">
	<div id="featured-wrapper">
		<div id="featured" class="extra2 margin-btm container">
			<div class="main-title">
				<h2>Почему это стоит внимания</h2>
				<span class="byline">Мы должны двигаться только вперед, даже если мы можем только ползти!</span> </div>
	
			<div class="ebox1"> <span class="fa fa-pagelines"></span>
				<div class="title">
					<h2>Становится лучше понимание</h2>
					<span class="byline">И это интересно знать</span> </div>
				<a href="#" class="button">+Усвоение</a> </div>
			<div class="ebox2"> <span class="fa fa-anchor"></span>
				<div class="title">
					<h2>Мини-задачи занимают не так много времени</h2>
					<span class="byline">Не сильно загружаем мозг в свободное время</span> </div>
				<a href="#" class="button">+Время</a> </div>
		</div>
	</div>
</div>
<div id="copyright" class="container">
	<p>&copy; Все права защищены, хотя тут нечего защищать.</p>
</div>
</body>
</html>
